# Default values for Laravel Appointments.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

phpfpm:
  repository: your-docker-repository
  tag: latest
  pullPolicy: Always

nginx:
  repository: nginx
  tag: alpine
  pullPolicy: IfNotPresent

database:
  host: your-database-host
  user: your-database-user
  password: your-database-password
  name: your-database-name

nginxService:
  name: nginx
  type: NodePort
  externalPort: 80
  internalPort: 80

phpfpmService:
  name: phpfpm
  type: NodePort
  port: 9000

ingress:
  enabled: true

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
