apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "laravel.name" . }}-nginx-vhost
  labels:
    app: {{ template "laravel.name" . }}-nginx-vhost
    chart: {{ template "laravel.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  laravel.conf: |-
    server {
        listen 0.0.0.0:{{ .Values.nginxService.internalPort }};

        server_name laravel-appointments.ctrlweb.dev;
        root /laravel/public;
        index index.php index.html index.htm;

        location / {
             try_files $uri /index.php?$args;
        }

        location ~ \.php$ {
            fastcgi_pass {{ .Chart.Name }}-phpfpm:9000;
            fastcgi_index index.php;
            include fastcgi_params;
        }

        access_log /dev/stdout;
        error_log /dev/stderr;
    }
