apiVersion: v1
kind: Secret
metadata:
  name: {{ template "laravel.fullname" . }}-db
  labels:
    app: {{ template "laravel.name" . }}
    chart: {{ template "laravel.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  db-host: {{ .Values.database.host | b64enc | quote }}
  db-name: {{ .Values.database.name | b64enc | quote }}
  db-password: {{ .Values.database.password | b64enc | quote }}
  db-user: {{ .Values.database.user | b64enc | quote }}
