apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "laravel.name" . }}-app
  labels:
    app: {{ template "laravel.name" . }}-app
    chart: {{ template "laravel.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "laravel.name" . }}-app
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "laravel.name" . }}-app
        release: {{ .Release.Name }}
    spec:
      volumes:
        - name: source-code
          emptyDir: {}
        - name: nginx-vhost
          configMap:
            name: {{ template "laravel.name" . }}-nginx-vhost
      containers:
        - name: {{ .Chart.Name }}-nginx
          image: "{{ .Values.nginx.repository }}:{{ .Values.nginx.tag }}"
          imagePullPolicy: {{ .Values.nginx.pullPolicy }}
          ports:
            - containerPort: {{ .Values.nginxService.internalPort }}
              protocol: TCP
          volumeMounts:
            - name: nginx-vhost
              mountPath: /etc/nginx/conf.d
            - name: source-code
              mountPath: /var/www/laravel
        - name: {{ .Chart.Name }}-phpfpm
          image: "{{ .Values.phpfpm.repository }}:{{ .Values.phpfpm.tag }}"
          imagePullPolicy: {{ .Values.phpfpm.pullPolicy }}
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "cp -r /var/www/laravel/. /laravel; composer install; php artisan key:generate; chmod -R 777 /laravel; chmod -R 777 /var/www/laravel;"]
          ports:
            - containerPort: {{ .Values.phpfpmService.port }}
              protocol: TCP
          volumeMounts:
            - name: source-code
              mountPath: /laravel
