{{- if .Values.ingress.enabled -}}
{{- $name := include "laravel.name" . -}}
{{- $ingressPath := .Values.ingress.path -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $name }}-ingress
  labels:
    app: {{ template "laravel.name" . }}-ingress
    chart: {{ template "laravel.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  backend:
    serviceName: {{ $name }}-app
    servicePort: 80
{{- end }}
