apiVersion: v1
kind: Service
metadata:
  name: {{ template "laravel.name" . }}-app
  labels:
    app: {{ template "laravel.name" . }}-app
    chart: {{ template "laravel.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.nginxService.type }}
  selector:
    app: {{ template "laravel.name" . }}-app
    release: {{ .Release.Name }}
  ports:
    - port: {{ .Values.nginxService.externalPort }}
      # targetPort: {{ .Values.nginxService.internalPort }}
      protocol: TCP
